### ISSUE TITLE
Uploading NON existing APK for analysis stays on uploader page

### ISSUE THREAD

**Issue by PedroCisnerosSantana** [Koodous/Koodous-issues#18]
![image](https://user-images.githubusercontent.com/37348419/76682106-7278c180-65f9-11ea-8201-80916ec01f45.png)

**Comment by Nekmo** [comment]
The incident has been resolved. Thank you!

**Comment by PedroCisnerosSantana** [comment]
Hello, still having this issue:
![image](https://user-images.githubusercontent.com/37348419/76759767-a46e5d00-678c-11ea-96e8-eeb9b62920fd.png)

If it can helps I'm using Google Chrome version 80.0.3987.132

Thanks

**Comment by wesinator** [comment]
#16 
I haven't experienced this recently in Firefox
